services:
  bootstrap:
    environment:
      APP_URL: http://127.0.0.1:${APP_PORT:-18080}
      GAME_WORLD_URL: http://127.0.0.1:${APP_PORT:-18080}/game/

  app:
    environment:
      APP_URL: http://127.0.0.1:${APP_PORT:-18080}
      GAME_WORLD_URL: http://127.0.0.1:${APP_PORT:-18080}/game/
    ports: !override
      - "127.0.0.1:${APP_PORT:-18080}:80"

  worker:
    environment:
      APP_URL: http://127.0.0.1:${APP_PORT:-18080}
      GAME_WORLD_URL: http://127.0.0.1:${APP_PORT:-18080}/game/
